version: '3.6'
services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'
  application:
    build: .
    ports:
      - '9999:9999'
    depends_on:
      - db
    volumes:
      - '.:/app-node'
